FROM python:3.12-slim

RUN python -m pip install requests~=2.31.0 python-dotenv~=1.0.1 pytz==2024.1 black==24.3.0 pylint==3.1.0

CMD [ "black", "--skip-string-normalization", "--verbose", "--line-length", "120", "bot" ]
